%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Constants from the Dynamixel Pro control table
% By: Federico Parietti
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%Define global variables
global  ADDRESS_TORQUE_ENABLE    BYTES_TORQUE_ENABLE
global  ADDRESS_RED_LED          BYTES_RED_LED
global  ADDRESS_GOAL_ACCEL       BYTES_GOAL_ACCEL
global  ADDRESS_GOAL_POS         BYTES_GOAL_POS
global  ADDRESS_VELOCITY_I_GAIN  BYTES_VELOCITY_I_GAIN
global  ADDRESS_POSITION_P_GAIN  BYTES_POSITION_P_GAIN
global  ADDRESS_GOAL_TORQUE      BYTES_GOAL_TORQUE
global  ADDRESS_OPERATING_MODE   BYTES_OPERATING_MODE
global  ADDRESS_PRES_POS         BYTES_PRES_POS
global  ADDRESS_PRES_CURR        BYTES_PRES_CURR
global  ADDRESS_GOAL_VEL         BYTES_GOAL_VEL
global  ADDRESS_PRES_VOLT        BYTES_PRES_VOLT
global  ADDRESS_PRES_TEMP        BYTES_PRES_TEMP

global  RAD2POS       POS2RAD

%Control Table Values
ADDRESS_OPERATING_MODE = 11;
BYTES_OPERATING_MODE = 1;

ADDRESS_TORQUE_ENABLE = 562;
BYTES_TORQUE_ENABLE = 1;

ADDRESS_RED_LED = 563;
BYTES_RED_LED = 1;

ADDRESS_VELOCITY_I_GAIN = 586;
BYTES_VELOCITY_I_GAIN   = 2;

ADDRESS_POSITION_P_GAIN = 594;
BYTES_POSITION_P_GAIN   = 2;

ADDRESS_GOAL_POS = 596;
BYTES_GOAL_POS = 4;

ADDRESS_GOAL_TORQUE = 604;
BYTES_GOAL_TORQUE   = 2;

ADDRESS_GOAL_ACCEL = 606;
BYTES_GOAL_ACCEL = 4;

ADDRESS_PRES_POS = 611;
BYTES_PRES_POS = 4;

ADDRESS_PRES_CURR = 621;
BYTES_PRES_CURR   = 2;

ADDRESS_GOAL_VEL = 600;
BYTES_GOAL_VEL = 4;

ADDRESS_PRES_VOLT = 623;
BYTES_PRES_VOLT = 2;

ADDRESS_PRES_TEMP = 625;
BYTES_PRES_TEMP = 1;

%Conversion gains
RAD2POS = 251000/pi;
POS2RAD = pi/251000;


